title: "Shikara CMS"
description: "CMS statis gratis dengan Jekyll + Prose.io"
baseurl: ""
url: "https://rafifsadid.my.id"
collections:
  articles:
    output: true
markdown: kramdown
permalink: /artikel/:slug/
excerpt_separator: "<!-- more -->"
theme: null                      # kita custom sendiri
